<?php

namespace IKNSA\BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastInserted($entity, $amount)
    {
        return $this->getEntityManager()
                    ->createQuery(
                        "SELECT e.id, e.title, e.summary, e.createdAt, e.extension, u.username FROM $entity e JOIN e.user u ORDER BY e.id DESC"
                    )
                    ->setMaxResults($amount)
                    ->getResult();
    }
}
